#!/bin/bash
#
# tty-keepalive
# 
# simulate tty activity in background to prevent 
# stale connection (firewall timeout...)
# 
# Author: joknarf
#
# tty-keepalive sends an OSC visual bell each <SECONDS>
# (totally ignored by most tty emulators)
# exits when pseudo tty dies
#
# usage: tty-keepalive [<SECONDS>]
#        tty-keepalive stop
#
# to add in shell rc-file:
# tty-keepalive [<SECONDS>]
#
[ "$1" = -h ] && echo "usage: ${0##/} [<SECONDS>]" && exit 0
[ -t 1 ] || exit 0
DEVPTS=$(tty 2>/dev/null)
[ "$DEVPTS" ] || exit 1
[ -w "$DEVPTS" ] || exit 1
PTS=${DEVPTS#/dev/}
[ "$1" = stop ] && {
  pkill -t $PTS -f "tty-keepalive $PTS"
  exit
}

[ ! "$_TTY_EXEC" ] && {
  pgrep -t $PTS -f "tty-keepalive $PTS" >/dev/null 2>&1 && exit
  _TTY_EXEC=1 exec "$0" "$PTS" "$@"
}
shift
SLEEP=${1-120}
TTY_CODE='\033]9;0\a' # Visual Bell
printf "$TTY_CODE" 2>/dev/null >/dev/tty || exit 0
(
  cleanup()
  {
    trap - HUP INT TERM EXIT
    kill 0
  }
  trap cleanup HUP INT TERM EXIT
  while :; do
    sleep $SLEEP &
    wait
    [ -w "$DEVPTS" ] || break
    printf "$TTY_CODE" 2>/dev/null >/dev/tty || break
  done
) >/dev/null 2>&1 </dev/null &
