#!/bin/bash
#
# tty-keepalive
# 
# simulate tty activity in background to prevent 
# stale connection (firewall timeout...)
# 
# Author: joknarf
#
# tty-keepalive sends an OSC visual bell each <SECONDS>
# (totally ignored by most tty emulators)
# exits when pseudo tty dies
#
# usage: eval $(tty-keepalive [<SECONDS>])
#        eval $(tty-keepalive stop)
#
# to add in shell rc-file:
# eval $(tty-keepalive [<SECONDS>])
#
[ "$1" = -h ] && echo "usage: ${0##/} [<SECONDS>]" && exit 0
[ "$1" = stop ] && {
  [ "$TTYK_PID" ] && kill "$TTYK_PID" 2>/dev/null
  echo "unset TTYK_PID"
  exit 0
}
[ "$TTYK_PID" ] && kill -0 "$TTYK_PID" 2>/dev/null && exit 0
DEVPTS=$(tty 2>/dev/null)
[ "$DEVPTS" ] || exit 1
[ -w "$DEVPTS" ] || exit 1
SLEEP=${1-120}
TTY_CODE='\033]9;0\a' # Visual Bell
printf "$TTY_CODE" 2>/dev/null >/dev/tty || exit 1
unset spid
bash <<EOF >/dev/null 2>&1 &
  enable -f /usr/lib/bash/sleep sleep
  builtin sleep 0 || sleep() { /bin/sleep $SLEEP & spid=\$!; wait; }
  cleanup()
  {
    trap - HUP INT TERM EXIT
    ((spid)) && kill \$spid
    exit
  }
  trap cleanup HUP INT TERM EXIT
  while :; do
    sleep $SLEEP
    [ -w "$DEVPTS" ] || break
    printf "$TTY_CODE" 2>/dev/null >"$DEVPTS" || break
    printf "$TTY_CODE" 2>/dev/null >/dev/tty || break
  done
) 
EOF
echo export TTYK_PID="$!"
